spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update   # 👈 This tells Hibernate to create the 'products' table on startup
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      max-history: 7

eureka:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true