#spring.application.name=product

spring:
  application:
    name: product-service

  config:
    import: configserver:http://localhost:8084
  profiles:
    active: dev


#  jpa:
#    database: POSTGRESQL
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081