#spring.application.name=product

spring:
  application:
    name: product-service

  config:
    import: configserver:http://localhost:8084
  profiles:
    active: dev


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081